pip install --upgrade pip
pip install --upgrade setuptools
pip install --upgrade wikipedia
pip install --upgrade DateTime
pip install --upgrade chromadb
pip install --upgrade docarray
pip install --upgrade pandas
pip install --upgrade pydub
pip install --upgrade pypdf 
pip install --upgrade python-dotenv
pip install --upgrade tiktoken
pip install --upgrade yt_dlp
pip install --upgrade lark
pip install --upgrade scikit-learn
pip install --upgrade httpx[socks]
pip install --upgrade panel
pip install --upgrade jupyterlab
pip install --upgrade jupyter_bokeh
pip install --upgrade matplotlib
pip install --upgrade hvplot
pip install --upgrade openai
pip install --upgrade langchain
pip install --upgrade langchain-openai
pip install --upgrade langchain_experimental
pip install --upgrade langchain_community
# pip install --upgrade distribute
pip install --upgrade xlrd
pip install --upgrade openpyxl
pip install --upgrade ipdb
pip install --upgrade ipykernel
pip install --upgrade huggingface-hub
pip install --upgrade transformers
pip install --upgrade accelerate
pip install --upgrade lxml
pip install --upgrade numexpr
pip install --upgrade ctransformers
pip install --upgrade mistralai
pip install --upgrade plotly
pip install --upgrade PySide6
pip install --upgrade pyqt6
pip install --upgrade requests
pip install --upgrade fbs 
# pip install --upgrade PyInstaller==3.4
# pip uninstall PyInstaller
pip install --upgrade playwright
pip install --upgrade html2text
pip install --upgrade bs4
pip install --upgrade pytesseract
pip install --upgrade scrapy
pip install --upgrade pillow
pip install --upgrade jq
pip install --upgrade selenium
pip install --upgrade numpy
pip install --upgrade torch
pip install --upgrade torchdata
pip install --upgrade torchtext
pip install --upgrade spacy
pip install --upgrade altair
pip install --upgrade jupytext
pip install --upgrade flake8
pip install --upgrade black
pip install --upgrade GPUtil
pip install --upgrade wandb
pip install --upgrade graphviz
pip install --upgrade pygraphviz
pip install --upgrade fastapi 
pip install --upgrade uvicorn 
pip install --upgrade celery 
pip install --upgrade redis 
pip install --upgrade pydantic 
pip install --upgrade sqlalchemy 
# pip install --upgrade psycopg2
pip install --upgrade psycopg2-binary
pip install --upgrade pyverilog
pip install --upgrade streamlit
pip install --upgrade llama-cpp-python
pip install --upgrade huggingface-hub
